version: '3.8'

services:
  typescript:
    build:
      context: ./node.js
      dockerfile: Dockerfile
    container_name: typescript-runner
    volumes:
      - ../src:/usr/src/app   # src ディレクトリをコンテナにマウント
