services:
  typescript:
    build:
      context: ./node.js
      dockerfile: Dockerfile
    container_name: typescript-runner
    volumes:
      - ..:/usr/src/app   # src ディレクトリをコンテナにマウント
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
